replicaCount: 2

image:
  repository: YOURACR.azurecr.io/go-web
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: go-web.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
