apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-web.fullname" . }}
  labels: {{- include "go-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "go-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "go-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: go-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
